// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3BJBjFSYRGAwR8QdeHAvLRr7j-aB31KM',
    appId: '1:1007897565042:web:aa42b4861f4c98bacfefeb',
    messagingSenderId: '1007897565042',
    projectId: 'food-e9bc2',
    authDomain: 'food-e9bc2.firebaseapp.com',
    storageBucket: 'food-e9bc2.appspot.com',
    measurementId: 'G-XV7MGXMBM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-iXlpEi6urpZoli3FM2Mt0y42aApvSXU',
    appId: '1:1007897565042:android:e0a3bb8652851772cfefeb',
    messagingSenderId: '1007897565042',
    projectId: 'food-e9bc2',
    storageBucket: 'food-e9bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDfQiRBnAg6MErzC_XmzhvQEwgNh_RQbM',
    appId: '1:1007897565042:ios:01fa4d29d1df093dcfefeb',
    messagingSenderId: '1007897565042',
    projectId: 'food-e9bc2',
    storageBucket: 'food-e9bc2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDfQiRBnAg6MErzC_XmzhvQEwgNh_RQbM',
    appId: '1:1007897565042:ios:505a79e148edeabfcfefeb',
    messagingSenderId: '1007897565042',
    projectId: 'food-e9bc2',
    storageBucket: 'food-e9bc2.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp.RunnerTests',
  );
}
